version: '3'
services:

  # Database for LRS statements
  postgres:
    restart: always
    build: 
      context: postgres
    ports:
      - "5482:5482"
    container_name: docker_postgres
    # Persist this data between sessions
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  # Required for activity metadata
  amqp:
    restart: always
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    container_name: docker_rabbit
    ports:
      - "15672:15672"
      - "14672:14672"
  
  # The actual ADL LRS service run through uWSGI
  lrs:
    restart: always
    build: 
      context: lrs
    ports:
      - "9000:9000"
    container_name: docker_lrs
    links:
      - postgres
      - amqp
  
  # nginx proxy used to handle LRS traffic
  nginx:
    restart: always
    build: 
      context: nginx
    ports:
      - "23:23"
      - "8443:8443"
    container_name: docker_nginx
    links:
      - lrs


      
